name: CI
on:
  push:
jobs:
  build-test-job:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --cpus 1
    steps:
      - name: checkout
        uses: "actions/checkout@v4"
      - name: Run Build Test
        run: ./scripts/run_build_test.sh
